### ISSUE TITLE
Lock might be acquired by multiple tabs upon refresh

### ISSUE THREAD

**Issue by shaharmor** [supertokens/browser-tabs-lock#9]
Hi,

I am trying to use this library for cross tab locking, and I noticed that upon refresh, the lock might be acquired by multiple tabs at the same time.

Given this simple page:

```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <script src="https://cdn.jsdelivr.net/gh/supertokens/browser-tabs-lock@1.2/bundle/bundle.js"></script>
  <script>
  const lock = new supertokenslock.getNewInstance();

  window.addEventListener('beforeunload', async () => {
    await lock.releaseLock('lock-key');
  });

  (async () => {
    console.log(`Acquiring lock`);
    let acquired = false;
    do {
      acquired = await lock.acquireLock('lock-key', 5000);
    } while (!acquired);
    console.log(`Acquired lock`);
  })();
  </script>
</head>
<body>
</body>
</html>
```

If you open it in two tabs, the first one will acquire the lock, and the second one will wait.

Once you refresh the first tab, the second tab will acquire the lock, and also the first one (Once it finishes the refresh).

The only way I could mitigate it was by adding some random delay before the first call to `acquireLock()`, like this:

```js
(async () => {
    console.log(`Acquiring lock`);
    let acquired = false;
	await new Promise((resolve) => setTimeout(resolve, Math.floor(Math.random() * 101)));
    do {
      acquired = await lock.acquireLock('lock-key', 5000);
    } while (!acquired);
    console.log(`Acquired lock`);
  })();
```

Any suggestions?

**Comment by rishabhpoddar** [comment]
Interesting! I'll have a look at it. Thanks for pointing it out.

**Comment by rishabhpoddar** [comment]
FIxed in version 1.2.7. You can continue to use your current script URL as browser-tabs-lock@1.2 should fetch browser-tabs-lock@1.2.7 since that's the latest version. You may need to hard reset your cache though.

**Comment by shaharmor** [comment]
Did you figure out why is it happening?

**Comment by rishabhpoddar** [comment]
This was quite a strange edge case to be honest. I'm not entirely sure what caused this to happen, but here is the only reasoning (however unlikely) I can think of: 
- Once a tab releases a lock (tab `a`), its entry in the localstorage is removed. We expect this to be an atomic operation having consistent results across all tabs.
- The other tab (tab `b`) which was previously trying to acquire the lock now tries and is able to "start" acquiring the lock (since it sees `null` in localstorage).
- While the above is happening, tab `a` finishes refreshing and is also attempting to acquire the lock. Here, we expect that this tab `a` will see the information put in the localstorage by tab `b` and not acquire the lock. However, tab `a` was seeing `null`. 
- This is OK, but after tab `a` writes to localstorage, the tab `b` should fail (since after a random delay, tab `b` reads the locastorage to check that it was indeed the last one to write to it).
- For some strange reason, both, tab `b` and tab `a` thought they were the last ones to write to the localstorage.
- After much experimentation, I figured it's to do with the inital localstorage read and the fact that both tabs are seeing `null`. So I added a delay there that is just a little greater than the amount of time it takes to write to localstorage and then this issue disappeared.

While this sort of an issue does not happen in normal scenarios (when two tabs are trying to acquire the lock at the same time without a page refresh involved), for some reason, the refreshing had caused it to break. So this makes me wonder if something unexpected is happening when we write to localstorge while unloading the page. 

I'm not sure if I completely answered your question, but if you have a better reasoning or a better solution, please feel free to let me know! Thanks

**Comment by shaharmor** [comment]
I wonder if this is something Chrome specific, or cross browser.
If its Chrome only, it might be worth it to open a cr bug

**Comment by rishabhpoddar** [comment]
Yea. Perhaps I will do that when I get time. For now, this issue seems to be fixed :)
